"""empty message

Revision ID: 3ad3a1c8f6fe
Revises: 2a25ae503db0
Create Date: 2022-08-09 20:59:44.192487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad3a1c8f6fe'
down_revision = '2a25ae503db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('want_read_books', 'book_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('want_read_books', 'book_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
